#Curation fields
DETAILS = 'details'
SERVERS = 'servers'
PROJECT = 'project'
INFO = 'info'
REFERENCE = 'reference'
CHARTS = 'charts'
TOOLS = 'tools'
DATASETS = 'datasets'
SCRIPTS = 'scripts'
DOCUMENTATION = 'documentation'
WORKFLOW = 'workflow'
HEADS = 'heads'
EDGES = 'edges'
VERSIONS = 'versions'
